spring:
  application:
    name: products-api

messaging:
  mq:
    request-queue: in01.products.request
    response-queue: in01.products.response

ecommerce:
  products:
    cache-ttl-seconds: 300
    max-page-size: 50
