spring:
  application:
    name: orders-api

logging:
  level:
    com.ecommerce.orders: INFO

messaging:
  mq:
    request-queue: gb01.orders.request
    response-queue: gb01.orders.response

kubernetes:
  resources:
    requests:
      cpu: "500m"
      memory: "512Mi"
  replicas: 2

ecommerce:
  orders:
    max-items-per-order: 50
    idempotency-window-minutes: 5
