spring:
  application:
    name: products-api

messaging:
  mq:
    request-queue: gb01.products.request
    response-queue: gb01.products.response

ecommerce:
  products:
    cache-ttl-seconds: 600
    max-page-size: 100
